name: CD
on:
  release:
     types: [published]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod spec lint
        pod trunk push RookSDK.podspec
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
